version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
   commit_message:
      prefix: "feat"
      prefix_development: "build"
      include_scope: true
  open-pull-requests-limit: 10
