name: Build

on:
  merge_group:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@064fe7f3312418007dea2b49a19844a9ee378f49 # v6.0.2
        with:
          fetch-depth: 0

      - uses: linz/action-setup-node@aefd5d1f70cf979b1c9a51cdf47169ede423d325 # v1.0.7
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'
          scope: '@linzjs'

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test
