name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org

      - name: Install
        run: yarn

      - name: Build
        run: yarn run build

      - name: Lint
        run: yarn run lint

      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/v')
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN_LINZJS}}
