on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          release-type: node
          token: ${{ secrets.LINZ_GITHUB_AUTOMATION }}

  publish-release:
    permissions:
      contents: read
      id-token: write

    environment:
      name: prod

    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # v6.0.2
        with:
          fetch-depth: 0

      - uses: linz/action-setup-node@d492fdef8b09cc595b9e28408344de3f70076591 # v1.0.4
        with:
          node-version-file: .node-version

      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm run test

      - name: Publish to NPM
        run: npm publish
